image: maven:3.3.9

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -B clean install # -B batch mode makes Maven less verbose
          - mvn sonar:sonar  -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_USER -Dsonar.password=$SONAR_PWD